<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('PDF Archival');?></title>
		<link href="../js/datepicker/jquery.datepick.css" rel="stylesheet"/>
                <?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		?>
                <script src="../js/datepicker/jquery.plugin.js"></script>
<script src="../js/datepicker/jquery.datepick.js"></script>

<script src="../bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css" />

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
                                        deferRender: true,
                                        "deferRender": true,
					"sPaginationType": "full_numbers",
                                        "order": [[ 0, "desc" ]],
                                         "aaSorting": [[0, 'desc']]
				});
			} );
		</script>
	</head>
    <style type="text/css">
        
        select{
            
      
           
        }
   
tr{
    cursor:default !important;
}
h2,h3{
            font-size: 16px !important;
        }
        select, input[type="text"] {
    color: black !important;
}
        </style>
      
	<body class="yui-skin-sam" >
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
			<div id="content">
                             <div clas="row">
				<div id="subcontent">
                                    <div class="row">
					<div id="contentheader">
						<h2><?php tp('Request User Access ');?></h2><br>
                                                   
                                        </div>
					</div>
                                    <div class="row">
                                     <div id="statusMessage">
                                <?php echo (!empty($this->statusMessage))?  '<div id="statusBox">'.$this->statusMessage.'</div>':""; ?>
                            </div>
                                    </div>
					<div class="pad20 clear"></div>
					
                                    
                                    
                                   
                                   
                                        <div class="col-md-11" style="margin:0 auto;">
                                        <?php
 //print_r($this->tocktack);

if (isset($this->outputs)) {
	if (count ($this->outputs) == 0){
            echo 
            '<br/>
            <h2><b>Archived PDF Reports</b></h2>';
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
		if(!empty($this->outputs)){
?>

				
                                   
                                    <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php if(!empty($this->headers)){
		foreach ($this->headers as $key=>$value){
			echo "							<th> $value </th>\n";
		}
	}
?>
						</tr>
					</thead>
					<tbody>
<?php
 	$url="";
        $declineUrl="";
        global $url,$declineUrl;
		foreach ($this->outputs as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
                            if($key=="req_id"){
                                $url = $this->baseUrl."user/approve/req_id/$value";
                                $declineUrl = $this->baseUrl."user/requestaccess/decline/$value";
                                $link = "<a href='$url'>$value</a>";
                                echo "				   			<td>" . $link . "</td>\n";
                            }
                            else if($key=="status"){
                                if($value==0){
                                $link = "<a href='$url'>Approve</a> &nbsp;&nbsp;&nbsp;&nbsp;<a href='$declineUrl'>Decline</a>";
                                }else if($value==1){
                                    $link = "Approved";
                                }
                                else if($value==-1){
                                    $link = "Declined";
                                }
                                echo "				   			<td>" . $link . "</td>\n";
                            }
                            else{
				echo "				   			<td>" . $value . "</td>\n";
                            }
			}
			echo "						</tr>\n";
		}
	
?>
					</tbody>
				</table>
				
<?php
	}
}
}
?>
                                    </div>
                                    </div>
					<div class="clear" style=""></div>
				</div>
				<div class="clear" style=""></div>
			</div> 
                        </div>
			<div class="clear" style="height : 100px;"></div>
			<div class="clear" style=""></div>
				
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
	</body>
</html>






